seed: 42
num_workers : 4

model_name    : 'sgaligner'
modules       : ['point', 'gat'] # GAIA originally it was ['point', 'gat', 'rel', 'attr'], but I just need point and gat for my aims
use_predicted : False
registration  : False
scan_type     : 'subscan'

data :
  name            : Scan3R
  root_dir        : /local/home/gmarsich/Desktop/3RScan
  label_file_name : labels.instances.align.annotated.v2.ply
  pred_subfix     : inseg.ply

preprocess :
  pc_resolutions      : [64, 128, 256, 512]
  subscenes_per_scene : 2 # GAIA initially it was 7, but for the work I need to do with Replica I have to try with 2
  filter_segment_size : 512
  min_obj_points      : 200 # GAIA was 50, but I tried to modify it
  anchor_type_name    : '' 

model :
  rel_dim             : 9 # GAIA OBS.: the original checkpoint is with 41, but it is not relevant for my purpose (I don't have labels on the edges)
  attr_dim            : 164
  alignment_thresh    : 0.4

train :
  batch_size          : 2

val :
  batch_size          : 1 # GAIA was 4, but for the work I need to do in Replica better to try with 1, NOT WORKING, HAD TO MODIFY FROM THE yaml file
  overlap_low         : 0.0
  overlap_high        : 0.0

val :
  pc_res : 512